"""Add progress relationships

Revision ID: 12d75c5a0b4c
Revises: e011e0d77c7d
Create Date: 2025-03-27 23:14:34.259774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d75c5a0b4c'
down_revision: Union[str, None] = 'e011e0d77c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
