"""add_logo_to_projects

Revision ID: 16dae8fd7006
Revises: 92f778d71ded
Create Date: 2025-05-17 13:40:16.899086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16dae8fd7006'
down_revision: Union[str, None] = '92f778d71ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('logo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'logo')
    # ### end Alembic commands ###
