"""add assignee in task table

Revision ID: 5d9607795ef2
Revises: a59732e05d87
Create Date: 2025-02-18 18:55:48.683575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9607795ef2'
down_revision: Union[str, None] = 'a59732e05d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=10), nullable=True))
    op.add_column('tasks', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assignee_id')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
