"""add_cascade_delete

Revision ID: 66bc70f3effb
Revises: 1dd2254e133f
Create Date: 2025-04-16 10:56:08.308725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bc70f3effb'
down_revision: Union[str, None] = '1dd2254e133f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_index('ix_project_activities_created_at', table_name='project_activities')
    op.drop_index('ix_project_activities_project_id', table_name='project_activities')
    op.drop_constraint('task_columns_project_id_fkey', 'task_columns', type_='foreignkey')
    op.create_foreign_key(None, 'task_columns', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_columns', type_='foreignkey')
    op.create_foreign_key('task_columns_project_id_fkey', 'task_columns', 'projects', ['project_id'], ['id'])
    op.create_index('ix_project_activities_project_id', 'project_activities', ['project_id'], unique=False)
    op.create_index('ix_project_activities_created_at', 'project_activities', ['created_at'], unique=False)
    op.create_index('ix_notifications_read', 'notifications', ['read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###
