"""Add color

Revision ID: 77a592ad2eb5
Revises: 3df429e3ac37
Create Date: 2025-03-10 14:22:58.083730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a592ad2eb5'
down_revision: Union[str, None] = '3df429e3ac37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_columns', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_columns', 'color')
    # ### end Alembic commands ###
