"""add_is_private_in_project

Revision ID: 9bf680dd3061
Revises: d2fa875c7168
Create Date: 2025-06-08 15:59:13.439418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf680dd3061'
down_revision: Union[str, None] = 'd2fa875c7168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_private', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_private')
    # ### end Alembic commands ###
