"""add_task_relations_table

Revision ID: c6b2f725a367
Revises: c15c1f2f07f6
Create Date: 2025-05-25 15:31:02.571015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b2f725a367'
down_revision: Union[str, None] = 'c15c1f2f07f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_task_id', sa.Integer(), nullable=False),
    sa.Column('target_task_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('RELATED', 'PARENT', 'CHILD', name='taskrelationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_relations')
    # ### end Alembic commands ###
