"""add_grading_fields

Revision ID: d2fa875c7168
Revises: 1808e3fb8956
Create Date: 2025-05-30 23:32:41.650740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fa875c7168'
down_revision: Union[str, None] = '1808e3fb8956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_grading_settings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_grading_settings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('project_grading_settings_project_id_key', 'project_grading_settings', type_='unique')
    op.drop_constraint('project_grading_settings_project_id_fkey', 'project_grading_settings', type_='foreignkey')
    op.create_foreign_key(None, 'project_grading_settings', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('completion_status', sa.Enum('COMPLETED', 'PARTIAL', 'NOT_COMPLETED', name='taskcompletionstatus'), nullable=True))
    op.add_column('tasks', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'score')
    op.drop_column('tasks', 'completion_status')
    op.drop_constraint(None, 'project_grading_settings', type_='foreignkey')
    op.create_foreign_key('project_grading_settings_project_id_fkey', 'project_grading_settings', 'projects', ['project_id'], ['id'])
    op.create_unique_constraint('project_grading_settings_project_id_key', 'project_grading_settings', ['project_id'])
    op.drop_column('project_grading_settings', 'updated_at')
    op.drop_column('project_grading_settings', 'created_at')
    # ### end Alembic commands ###
