"""fix enum types

Revision ID: e011e0d77c7d
Revises: 2d8502f2630c
Create Date: 2025-03-24 21:32:24.162051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e011e0d77c7d'
down_revision: Union[str, None] = '2d8502f2630c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_progress', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_project_progress', 'created_at')
    # ### end Alembic commands ###
