"""add_notification_indexes

Revision ID: f14fbbf32047
Revises: 66bc70f3effb
Create Date: 2025-04-16 14:51:28.093242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14fbbf32047'
down_revision: Union[str, None] = '66bc70f3effb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notifications_created_at', 'notifications', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    # ### end Alembic commands ###
